import React, { useEffect, useState } from "react";
import { useParams, useLocation } from "react-router-dom";
import "../styles/Memo.css";
import html2pdf from "html2pdf.js";
import { QRCodeSVG } from "qrcode.react";
import { renderEmptyRows } from "../utils/renderEmptyRows";

const { electron } = window;

const Memo = ({ memo_number: propMemoNumber }) => {
  const [items, setMemoItems] = useState([]); // state for memo items
  const [memoData, setMemoData] = useState(null); // state for memo header details
  const location = useLocation();
  const [notes, setNotes] = useState([]);

  // Detect whether current route is for printing
  const isPrintMode = location.pathname.includes("/invoice/print-memo/");

  useEffect(() => {
    console.log("Current path:", location.pathname);
  }, [location]);

  // Get memo_number from either prop or URL param
  const params = useParams();
  const memo_number = propMemoNumber || params.memo_number;

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [data, items] = await Promise.all([
          window.electron.fetchMemoData(memo_number),
          window.electron.fetchMemoItems(memo_number),
        ]);

        setMemoData(data[0]);
        setMemoItems(items);

        if (data[0]?.notes_added) {
          const notes = await window.electron.getNotesByIds(
            data[0].notes_added
          );
          setNotes(notes);
        }
      } catch (err) {
        console.error("Failed to fetch memo data or items:", err);
      }
    };

    if (memo_number) {
      fetchData();
    }
  }, [memo_number]);

  // If data not yet loaded — render nothing
  if (!memoData) return null;
  if (!items) return null;
  // Prepare QR Code content string
  const qrData =
    `Memo Number: ${memo_number}\n` +
    `Current Balance: ₹${memoData.balance}\n` +
    `This Memo is generated by uNCov Business Suite\n` +
    `Call Us +91-8275741506 for FREE DEMO`;

  const collectCss = () => {
    console.log("[PRINT] Collecting CSS from all stylesheets...");
    let css = "";
    const styleSheets = Array.from(document.styleSheets);
    styleSheets.forEach((sheet, i) => {
      console.log(
        `[PRINT] Processing stylesheet ${i + 1}/${styleSheets.length}`
      );
      try {
        const rules = sheet.cssRules ? Array.from(sheet.cssRules) : [];
        rules.forEach((r) => {
          css += r.cssText + "\n";
        });
      } catch (e) {
        console.warn(
          "[PRINT] Skipping inaccessible stylesheet:",
          sheet.href || "inline style",
          e
        );
      }
    });
    console.log("[PRINT] CSS collection complete. Length:", css.length);
    return css;
  };

  const buildFullHtml = (innerHtml) => {
    console.log("[PRINT] Building full HTML document...");
    const css = collectCss();
    const html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>Memo</title>
    <style>${css}</style>
  </head>
  <body>
    ${innerHtml}
  </body>
</html>`;
    console.log("[PRINT] Full HTML built. Size:", html.length);
    return html;
  };

  const handlePrint = async () => {
    console.log("[PRINT] Print process started...");
    try {
      const memoEl = document.querySelector(".memo-container");
      if (!memoEl) {
        console.error("[PRINT] Memo element not found.");
        throw new Error("Memo element not found");
      }
      console.log("[PRINT] Memo element found.");

      const memoHtml = memoEl.outerHTML;
      console.log("[PRINT] Memo HTML extracted. Length:", memoHtml.length);

      const fullHtml = buildFullHtml(memoHtml);
      const fileName = `memo_${memo_number || "preview"}`;
      console.log(`[PRINT] File name for printing: ${fileName}`);

      console.log("[PRINT] Sending HTML to Electron print helper...");
      const result = await window.electron.printMemo(fullHtml, fileName);

      console.log("[PRINT] Print helper returned:", result);
      if (result.success) {
        console.log("[PRINT] Print completed successfully.");
        await showSuccessDialog({
          title: "Print Complete",
          message: "Print completed successfully!",
        });
      } else {
        console.error(
          "[PRINT] Print helper reported failure. Code:",
          result.code
        );
        await showErrorDialog({
          title: "Print Failed",
          message: "Print failed. Error code: " + result.code,
        });
      }
    } catch (err) {
      console.error("[PRINT] Print process failed:", err);
      await showErrorDialog({
        title: "Print Failed",
        message: "Print failed: " + (err.message || err),
      });
    }
  };

  return (
    <div id="printable-area">
      {/* Only show print/download buttons if NOT in print mode */}
      {!isPrintMode && (
        <div className="memo-nav">
          <button onClick={handlePrint} className="print">
            <i className="bx bx-printer"></i> Print
          </button>

          <button
            className="download"
            onClick={() => {
              const MemoElement = document.querySelector(".memo-container");
              const opt = {
                margin: 0.5,
                filename: `memo_${memo_number || "preview"}.pdf`,
                image: { type: "jpeg", quality: 0.98 },
                html2canvas: { scale: 2 },
                jsPDF: { unit: "in", format: "a4", orientation: "portrait" },
              };
              html2pdf().set(opt).from(MemoElement).save();
            }}
          >
            <i className="bx bx-download"></i> Download
          </button>
        </div>
      )}

      {/* Main memo content */}
      <div className="memo-container">
        {/* Header: QR Code + Title */}
        <div className="memo-header">
          <div className="qr-code">
            <QRCodeSVG value={qrData} />
          </div>
          <div className="memo-title">
            <h2>R.I.S.</h2>
            <p>Ganesh Nagar, Gondia - 441601</p>
          </div>
        </div>

        {/* Memo metadata and customer info */}
        <div className="details">
          <div className="client-info">
            Customer Detail:
            <p className="client-name">{memoData.customer_name}</p>
            <p className="client-address">{memoData.customer_address}</p>
          </div>

          <div className="memo-meta">
            <p>
              <strong>Memo No.:</strong> {memoData.memo_number}
            </p>
            <p>
              <strong>Issue Date:</strong> {memoData.issueDate}
            </p>
            <p>
              <strong>Due Date:</strong> {memoData.dueDate}
            </p>
          </div>
        </div>

        {/* Item Table */}
        <table className="memo-table">
          <colgroup>
            <col className="col-no" />
            <col className="col-desc" />
            <col className="col-qty" />
            <col className="col-rate" />
            <col className="col-amount" />
          </colgroup>
          <thead>
            <tr>
              <th className="col-no">No.</th>
              <th className="col-desc">Description</th>
              <th className="col-qty">Qty</th>
              <th className="col-rate">Rate</th>
              <th className="col-amount">Amount</th>
            </tr>
          </thead>
          <tbody>
            {/* Map all memo items */}
            {items.map((item, idx) => (
              <tr key={idx}>
                <td className="col-no">{idx + 1}</td>
                <td className="col-desc">{item.description}</td>
                <td className="col-qty">
                  {item.quantity} {item.unit}
                </td>
                <td className="col-rate">{item.cost}</td>
                <td className="col-amount">{item.amount.toFixed(2)}</td>
              </tr>
            ))}

            {/* Add empty rows */}
            {renderEmptyRows(items.length + notes.length, 9, 5)}

            {notes.length > 0 && (
              <>
                <tr className="notes-header-row">
                  <td className="col-no">
                    <strong>*</strong>
                  </td>
                  <td className="col-desc">
                    <strong>Notes / Terms</strong>
                  </td>
                  <td className="col-qty"></td>
                  <td className="col-rate"></td>
                  <td className="col-amount"></td>
                </tr>

                {notes.map((note, idx) => (
                  <tr key={`note-${idx}`} className="note-row">
                    <td className="col-no"></td>
                    <td className="col-desc">
                      {note.notes_title}: {note.notes_content}
                    </td>
                    <td className="col-qty"></td>
                    <td className="col-rate"></td>
                    <td className="col-amount"></td>
                  </tr>
                ))}
              </>
            )}

            {/* Grand Total Row */}
            <tr className="grand-total-row">
              <td colSpan="4" className="grand-total-label">
                <strong>Grand&nbsp;Total</strong>
              </td>
              <td className="grand-total-value">
                ₹ {memoData.total.toFixed(2)}
              </td>
            </tr>
          </tbody>
        </table>
        <div className="summary-note">
          <em>This Memo is generated by uNCov Business Suite</em>
        </div>
        {/* Payment Summary */}
        <div className="summary-memo">
          <div className="summary-left">
            <strong>Amount Paid: </strong>
            <span>₹ {memoData.amount_paid.toFixed(2)}</span>
          </div>
          <div className="summary-right">
            <strong>Balance Due: </strong>
            <span>₹ {memoData.balance.toFixed(2)}</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Memo;
